openapi: 3.0.0
info:
  title: Bosch Smart Home Local API for Shutter
  description: |-
    This description focuses on the JSON-based, REST-like API for a Shutter.
    
    By using this documentation, the developer accepts and agrees to be bound by our [Terms and Conditions](https://github.com/BoschSmartHome/bosch-shc-api-docs#terms-and-conditions).
    
    This documentation is subject to the [Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode).
    
    Please report any issues you encounter with this documentation in our [GitHub tracker](https://github.com/BoschSmartHome/bosch-shc-api-docs/issues).
  version: "1.0"
servers:
  - url: https://{shcIp}:8444/smarthome
    description: "Bosch Smart Home Controller URL"
    variables:
      shcIp:
        default: 192.168.0.10
tags:
  - name: Services
    description: Services of your Shutter
  - name: States
    description: States of your Shutter
paths:
  '/devices/{deviceId}/services/ShutterControl':
    get:
      summary: Retrieve the ShutterControl service of the Shutter.
      description: |-
        Control of your shutter to take any position you desire.
      tags:
        - Services
      parameters:
        - $ref: '#/components/parameters/apiVersionHeaderParam'
        - $ref: '#/components/parameters/deviceIdPathParam'
      responses:
        '200':
          description: The ShutterControl was successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShutterControlService'
        '404':
          description: |-
            The entity could not be found. One of the defined query parameters was invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvancedError'
  '/devices/{deviceId}/services/ShutterControl/state':
    get:
      summary: Retrieve the state of the ShutterControl service.
      description: |-
        Retrieve the state of the ShutterControl service identified by the
        `deviceId` path parameter.
      tags:
        - States
      parameters:
        - $ref: '#/components/parameters/apiVersionHeaderParam'
        - $ref: '#/components/parameters/deviceIdPathParam'
      responses:
        '200':
          description: The state of ShutterControl was successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShutterControlServiceStates'
        '404':
          description: |-
            The entity could not be found. One of the defined query parameters was invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvancedError'

    put:
      summary: Executes the shutterControlState on the device.
      description: |-
        Executes the shutterControlState on the device identified by the `deviceId` path parameter.
      tags:
        - States
      parameters:
        - $ref: '#/components/parameters/apiVersionHeaderParam'
        - $ref: '#/components/parameters/deviceIdPathParam'
      responses:
        '204':
          description: Accepted request.
        '400':
          description: One of the defined query parameters was invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvancedError'
        '404':
          description: The entity could not be found. One of the defined path parameters was invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvancedError'
        '405':
          description: The method was not allowed.
        '422':
          description: Mapping of defined query parameter failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvancedError'
      requestBody:
        $ref: '#/components/requestBodies/ShutterControlServiceShutterControlStatePayload'
components:
  schemas:
    AdvancedError:
      type: object
      properties:
        '@type':
          type: string
          description: The type of the Object.
          example: JsonRestExceptionResponseEntity
        errorCode:
          type: string
          description: The error code of the occurred Exception.
        statusCode:
          type: integer
          description: The HTTP status of the error.
    ServiceDefinition:
      type: array
      minItems: 1
      uniqueItems: true
      items:
        type: string
        description: "A single fully qualified identifier of the Service of a Device."
      example:
        - ShutterControl
    ShutterControlServiceStates:
      type: object
      description: ShutterControlService states of Shutter
      properties:
        '@type':
          type: string
          enum: [shutterControlState]
          description: The type of the Object.
        level:
          $ref: '#/components/schemas/ShutterControlState'
    ShutterControlService:
      type: object
      properties:
        '@type':
          type: string
          enum: [DeviceServiceData]
          description: The type of the Object.
        id:
          type: string
          enum: [deviceServiceId]
          description: "A single fully qualified identifier of the Service of a Device."
        deviceId:
          type: string
          description: "A single fully qualified identifier of the Device."
        state:
          $ref: '#/components/schemas/ShutterControlServiceStates'
        path:
          type: string
          description: The path to the Property.
    ShutterControlState:
      type: string
      enum: ["0.000", "0.005", "...", "0.995", "1.000"]

  requestBodies:
    ShutterControlServiceShutterControlStatePayload:
      content:
        application/json:
          schema:
            type: object
            properties:
              '@type':
                type: string
                enum: [shutterControlState]
                description: The type of the Object.
              level:
                $ref: '#/components/schemas/ShutterControlState'
  parameters:
    apiVersionHeaderParam:
      in: header
      name: api-version
      description: The version of the API.
      schema:
        type: string
        example: "1.0"
    deviceIdPathParam:
      name: deviceId
      in: path
      description: "A single fully qualified identifier of the Device."
      required: true
      schema:
        type: string
    propertyPathPathParam:
      name: propertyPath
      in: path
      description: The path to the Property.
      required: true
      schema:
        type: string